NEUROSCIENCE_TOPICS = [
	(10042, "Neural and Behavioral Psychology Studies"),
	(10056, "Neurotransmitter Receptor Influence on Behavior"),
	(10077, "Neuroscience and Neuropharmacology Research"),
	(10182, "Child and Adolescent Psychosocial and Emotional Development"),
	(10214, "Psychotherapy Techniques and Applications"),
	(10314, "Social and Intergroup Psychology"),
	(10423, "Neurobiology and Insect Physiology Research"),
	(10465, "Neurobiology of Language and Bilingualism"),
	(10467, "Psychometric Methodologies and Testing"),
	(10475, "Psychological Well-being and Life Satisfaction"),
	(10509, "Religion, Spirituality, and Psychology"),
	(10565, "Psychopathy, Forensic Psychiatry, Sexual Offending"),
	(10608, "Neurogenesis and neuroplasticity mechanisms"),
	(10706, "Traumatic Brain Injury and Neurovascular Disturbances"),
	(10754, "Neuroendocrine Tumor Research Advances"),
	(10788, "Neuroscience and Music Perception"),
	(10813, "Sport Psychology and Performance"),
	(10814, "Neuropeptides and Animal Physiology"),
	(10826, "Behavioral and Psychological Studies"),
	(10853, "Anxiety, Depression, Psychometrics, Treatment, Cognitive Processes"),
	(10919, "Neurological disorders and treatments"),
	(10949, "Genetic Neurodegenerative Diseases"),
	(11040, "Personality Traits and Psychology"),
	(11079, "Creativity in Education and Neuroscience"),
	(11093, "Personality Disorders and Psychopathology"),
	(11118, "Evolutionary Psychology and Human Behavior"),
	(11132, "Psychoanalysis and Psychopathology Research"),
	(11173, "Neurofibromatosis and Schwannoma Cases"),
	(11266, "Neuroinflammation and Neurodegeneration Mechanisms"),
	(11274, "Botulinum Toxin and Related Neurological Disorders"),
	(11304, "Advanced Neuroimaging Techniques and Applications"),
	(11334, "Psychosomatic Disorders and Their Treatments"),
	(11456, "Neuroscience of respiration and sleep"),
	(11541, "Neuroendocrine regulation and behavior"),
	(11601, "Neuroscience and Neural Engineering"),
	(11627, "Autoimmune Neurological Disorders and Treatments"),
	(11735, "Peripheral Neuropathies and Disorders"),
	(11772, "Genetics and Neurodevelopmental Disorders"),
	(11953, "Neuroethics, Human Enhancement, Biomedical Innovations"),
	(12023, "Cholinesterase and Neurodegenerative Diseases"),
	(12061, "Axon Guidance and Neuronal Signaling"),
	(12226, "Neuroblastoma Research and Treatments"),
	(12249, "Veterinary Orthopedics and Neurology"),
	(12268, "Deception detection and forensic psychology"),
	(12308, "Mental Health and Psychiatry"),
	(12331, "Hereditary Neurological Disorders"),
	(12400, "Neurogenetic and Muscular Disorders Research"),
	(12430, "Academic and Historical Perspectives in Psychology"),
	(12464, "Neurological Complications and Syndromes"),
	(12476, "Intraoperative Neuromonitoring and Anesthetic Effects"),
	(12520, "Psychology of Moral and Emotional Judgment"),
	(12552, "Fetal and Pediatric Neurological Disorders"),
	(12553, "Psychedelics and Drug Studies"),
	(12621, "Hemispheric Asymmetry in Neuroscience"),
	(12622, "Neurosurgical Procedures and Complications"),
	(12666, "Historical Psychiatry and Medical Practices"),
	(12753, "Psychology, Coaching, and Therapy"),
	(12844, "Psychology and Mental Health"),
	(12848, "Psychological Testing and Assessment"),
	(12854, "Neurology and Historical Studies"),
	(12864, "Psychoanalysis and Social Critique"),
	(12882, "Jungian Analytical Psychology"),
	(12889, "Psychoanalysis, Philosophy, and Politics"),
	(12891, "Medicinal Plants and Neuroprotection"),
	(12947, "Health, psychology, and well-being"),
	(12963, "Anesthesia and Neurotoxicity Research"),
	(12993, "Psychology of Development and Education"),
	(13085, "Education, Psychology, and Social Research"),
	(13106, "Neuroscience, Education and Cognitive Function"),
	(13118, "Psychological Treatments and Disorders"),
	(13272, "Psychological Treatments and Assessments"),
	(13284, "Psychology Research and Bibliometrics"),
	(13447, "Educational and Psychological Assessments"),
	(13481, "Neurological diseases and metabolism"),
	(13521, "Psychosocial Factors Impacting Youth"),
	(13536, "Psychological and Temporal Perspectives Research"),
	(13680, "Education, Psychology, and Complexity Research"),
	(13701, "Psycholinguistics and Behavioral Studies"),
	(13730, "Martial Arts: Techniques, Psychology, and Education"),
	(13777, "Cognitive and psychological constructs research"),
	(13782, "Transactional Analysis in Psychotherapy"),
	(13796, "Neurological Disorders and Treatments"),
	(13841, "Psychology of Social Influence"),
	(13944, "Psychiatric care and mental health services"),
	(13966, "Neurological and metabolic disorders"),
	(14075, "Psychodrama and Leishmaniasis Studies"),
	(14104, "Developmental and Educational Neuropsychology"),
	(14144, "Neurological Disease Mechanisms and Treatments"),
	(14271, "Educational Methods and Psychological Studies"),
	(14273, "Cultural, Psychoanalytic, and Sociopolitical Reflections"),
	(14308, "Psychological and Educational Research Studies"),
	(14381, "Psychiatry, Mental Health, Neuroscience"),
	(14411, "Undergraduate Neuroscience Education and Research"),
	(14486, "Cardiovascular, Neuropeptides, and Oxidative Stress Research"),
]


TOPIC_ID_TO_NAME = {tid: name for tid, name in NEUROSCIENCE_TOPICS}
TOPIC_NAME_TO_ID = {name: tid for tid, name in NEUROSCIENCE_TOPICS} 