"use client";
import React, { useState } from "react";
import {
  Box,
  IconButton,
  Typography,
  Modal,
  Paper,
  Fab,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  useTheme,
  useMediaQuery,
} from "@mui/material";
import {
  Description as DocumentIcon,
  Close as CloseIcon,
  ExpandMore as ExpandIcon,
  ExpandLess as CollapseIcon,
} from "@mui/icons-material";

interface LegalDocument {
  title: string;
  content: string;
  icon: React.ReactNode;
}

const copyrightDisclaimer: LegalDocument = {
  title: "Copyright and Fair Use Disclaimer",
  content: `VergeSci Copyright and Fair Use Disclaimer
Effective Date: August 20th, 2025
Last Updated: August 20th, 2025

At VergeSci, Inc. ("VergeSci"), we respect the intellectual property rights of others and are committed to responsible content practices. This Copyright and Use Disclaimer clarifies how we handle publicly available content on the VergeSci platform.

1. Source Content Disclaimer
The VergeSci platform indexes and displays only the abstracts and associated metadata of scientific research articles that are either:
Published under open-access licenses,
Publicly distributed by governmental or non-commercial repositories (e.g., NIH, arXiv, Europe PMC), or
Otherwise made available for non-commercial research and educational reuse.
We do not scrape or distribute full-text articles unless explicitly permitted by the original source's license.

2. Use of Abstracts and Metadata
VergeSci does not transform the content or compete with the commercial market for research publications. We:
Limit collection to publicly available abstracts,
Attribute all content to the original publisher or database,
Provide access solely for academic, non-commercial discovery,
Do not monetize or redistribute the content outside of its original context.
Our indexing serves only to support users in locating, filtering, and exploring academic literature.

3. Copyright Claims
If you are a content owner and believe any abstract or metadata is misrepresented or should not be shown within the VergeSci platform, please contact us. We will respond promptly to any legitimate concerns and remove or revise the display of the content if necessary.
Please provide:
Your name and contact information,
A description of the content in question,
The URL or reference to the original article or dataset,
A statement of concern regarding the use of the material,
Your electronic or physical signature.
Contact:
Email: team@vergesci.com
Mailing Address: VergeSci, Inc., 318 Bonnie Brae Road, Hinsdale, Illinois, 60521

4. Responsibility of Users
Users of VergeSci are responsible for how they engage with linked or summarized materials. We encourage all users to access full content through official publishers or repositories and to respect the licensing terms of the original sources.

5. Non-Commercial and Attribution Focus
VergeSci operates as a non-commercial research support platform. Our system:
Does not enable downloading or exporting of original content,
Does not modify or adapt abstracts,
Always displays the original source and citation.
Our goal is to make it easier for researchers to identify relevant material while encouraging proper access through official channels.

6. Contact Us
Email: team@vergesci.com
Mailing Address: VergeSci, Inc., 318 Bonnie Brae Road, Hinsdale, Illinois, 60521
Thank you for supporting responsible scientific exploration and attribution.`,
  icon: <DocumentIcon />,
};

const termsOfService: LegalDocument = {
  title: "Terms of Service",
  content: `VergeSci Platform Terms of Service
Effective Date: August 20th, 2025
Last Updated: August 20th, 2025

These Service Terms ("Terms") govern your access to and use of the VergeSci platform and services ("Services"). By accessing or using the Services, you agree to be bound by these Terms. VergeSci, Inc. ("VergeSci") may update these Terms from time to time. VergeSci reserves the right to upgrade, update, or discontinue any feature or functionality of the Services in whole or in part. If VergeSci discontinues a core service in full during the term of a paid subscription, VergeSci will provide a replacement or offer a prorated refund.

1. RESEARCH SERVICES
1.1. Research Discovery & Summarization
You may use VergeSci's research tools to explore, filter, and summarize scientific publications, funding announcements, and datasets solely for lawful academic or professional research purposes. You may not:
Use the Services to train any competing artificial intelligence model;
Misrepresent any content generated by the platform as peer-reviewed or definitive scientific advice;
Resell, sublicense, or aggregate platform output for commercial resale.
1.2. Content Upload and User Data
If you submit documents or text ("User Data") to the platform (e.g., PDFs, article links, grant proposals), you grant VergeSci a non-exclusive, royalty-free, worldwide license to store, analyze, and process the content strictly for your use. You retain ownership of all uploaded content. VergeSci will not use your private uploads to train its AI models without your explicit consent.
1.3. Academic Collaborations
If you are using VergeSci under an institutional license (university, lab, or research organization), additional terms may apply via your institution. You are responsible for complying with your institutional data policies and for using the Services in accordance with academic integrity standards.
1.4. Funding Alerts and Integrations
You may use VergeSci to receive automated alerts on public or private research grants. You are responsible for verifying any funding opportunity before applying. VergeSci disclaims any guarantee regarding the continued availability, eligibility, or timeliness of grant listings. Third-party funding databases are subject to change.

2. LICENSES AND LIMITATIONS
2.1. Permitted Use
You are granted a limited, non-transferable license to access the Services for personal, academic, or internal business use. All rights not expressly granted are reserved by VergeSci.
2.2. Prohibited Activities
You agree not to:
Use the Services to infringe any third party's intellectual property rights;
Use automated means (e.g., bots, scrapers) to extract data, except via approved APIs;
Disrupt or degrade system performance for other users;
Post or transmit harmful, unlawful, defamatory, or misleading content.
2.3. AI-Generated Output
AI-generated summaries, suggestions, or annotations are provided "as-is" and do not substitute for peer-reviewed scientific review. VergeSci makes no warranties regarding the accuracy or fitness of such output.

3. ACCOUNTS AND ACCESS
3.1. Account Security
You are responsible for maintaining the confidentiality of your login credentials. You agree to notify VergeSci immediately of any unauthorized use of your account.
3.2. Access Tiers
Some Services may be free; others may require subscription or institutional access. VergeSci reserves the right to modify feature availability across plans.
3.3. Seat Usage and Reassignment
Each account (or "seat") is assigned to an individual user. Sharing credentials is prohibited. Organizations may reassign unused seats in accordance with their licensing agreement.

4. INTELLECTUAL PROPERTY
4.1. Ownership
The VergeSci platform and all underlying software, designs, logos, and content (excluding User Data) are the property of VergeSci or its licensors.
4.2. Feedback
You may submit feedback or suggestions regarding the Services. VergeSci may use such feedback without restriction or obligation to you.

5. THIRD-PARTY CONTENT AND LINKS
VergeSci may index or display content from third-party sources (e.g., PubMed, NIH RePORTER). Such content remains the intellectual property of their respective owners. VergeSci makes no representations about the accuracy or completeness of third-party content.

6. PRIVACY AND SECURITY
Your use of the Services is subject to our Privacy Policy. VergeSci employs reasonable security measures but cannot guarantee absolute data protection. Users are encouraged to avoid uploading sensitive personal or patient-identifiable data.

7. TERMINATION AND SUSPENSION
VergeSci reserves the right to suspend or terminate your access at its discretion for violation of these Terms. Upon termination, your license to access the Services immediately ceases. You may request an export of your data within 30 days.

8. DISCLAIMERS AND LIMITATION OF LIABILITY
The Services are provided "as-is" without warranties of any kind. VergeSci disclaims all implied warranties, including merchantability and fitness for a particular purpose. In no event shall VergeSci be liable for indirect, incidental, or consequential damages.

9. GOVERNING LAW AND DISPUTES
These Terms shall be governed by the laws of the State of Delaware, without regard to its conflict of law provisions. Any legal action shall be brought exclusively in the courts of Delaware.

10. CONTACT
For questions, please contact: team@vergesci.com`,
  icon: <DocumentIcon />,
};

const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  content: `VergeSci Privacy Policy
Effective Date: August 20th, 2025
Last Updated: August 20th, 2025

At VergeSci, Inc. ("VergeSci," "we," "us," or "our"), your privacy is a priority. This Privacy Policy explains how we collect, use, store, and share information when you use our platform (the "Service"). By using VergeSci, you agree to the practices described here.

1. Information We Collect
1.1 Information You Provide
Account Information: Your name, email address, institutional affiliation, and other registration details.
Uploaded Content: Research papers, proposals, datasets, or any other files submitted to the platform.
Communications: When you contact us directly, we may collect the contents of your message, including any attachments.
1.2 Information Collected Automatically
Usage Data: IP address, device type, browser type, pages visited, and access timestamps.
Cookies & Analytics: We use cookies and third-party tools (e.g., Google Analytics) to understand usage trends and improve the Service.
1.3 Information from Third Parties
Public Databases: We may collect research profiles and funding data from public or academic sources (e.g., ORCID, NIH RePORTER).
Institutional Integrations: If you access VergeSci through an institution, we may receive information from your university or lab with your consent.

2. How We Use Information
We use the information we collect to:
Provide, personalize, and improve the Service;
Respond to your inquiries and support requests;
Deliver research summaries, recommendations, and funding alerts;
Secure our platform and prevent abuse;
Conduct analytics and research to enhance platform performance;
Comply with legal obligations.

3. Sharing of Information
We do not sell your personal information. We may share your data in the following cases:
Service Providers: Trusted vendors who perform technical or operational functions (e.g., hosting, analytics) under confidentiality agreements.
Legal Compliance: To comply with laws, regulations, subpoenas, or lawful requests.
Institutional Partners: If your access is provisioned by an academic or research institution, we may share usage data with that entity.
Consent: With your explicit permission.

4. Your Rights & Choices
Depending on your jurisdiction, you may have the right to:
Access, update, or delete your personal information;
Opt out of non-essential communications;
Withdraw consent for data processing (where consent is the legal basis);
Request data portability.
To exercise these rights, please contact us at team@vergesci.com.

5. Data Retention
We retain your information only as long as necessary to:
Provide the Service;
Comply with legal obligations;
Resolve disputes and enforce agreements.
Upon account deletion, we will delete or anonymize your personal data, except where retention is legally required.

6. Data Security
We implement appropriate administrative, technical, and physical safeguards to protect your information. No system is entirely secure, so we encourage users to take precautions when uploading sensitive content.

7. Children's Privacy
VergeSci is not intended for users under 13 years of age. We do not knowingly collect personal data from children without parental consent. If you believe a child has provided us with data, contact us immediately.

8. International Users
If you access VergeSci from outside the U.S., you understand that your data will be transferred to and processed in the United States. If you are located in the EU, UK, or another region with laws governing data collection, we comply with applicable data protection laws, including the GDPR.

9. Changes to This Policy
We may revise this Privacy Policy from time to time. Material changes will be posted on this page, and we will notify users as required by law. Continued use of the Service after changes constitutes acceptance.

10. Contact Us
Questions or concerns? Reach out at:
Email: team@vergesci.com
Mailing Address: VergeSci, Inc., 318 Bonnie Brae Road, Hinsdale, Illinois, 60521

Thank you for trusting VergeSci with your research and data privacy.`,
  icon: <DocumentIcon />,
};

const documents = [copyrightDisclaimer, termsOfService, privacyPolicy];

// Function to format document content with better styling
const formatDocumentContent = (content: string): string => {
  return (
    content
      // Format main titles (lines that end with date)
      .replace(
        /^(.+?)\nEffective Date: (.+?)\nLast Updated: (.+?)\n/g,
        "<h1>$1</h1><p><strong>Effective Date:</strong> $2</p><p><strong>Last Updated:</strong> $3</p>"
      )
      // Format numbered sections (1., 2., etc.)
      .replace(/^(\d+)\.\s+(.+)$/gm, "<h2>$1. $2</h2>")
      // Format subsections (1.1, 1.2, etc.)
      .replace(/^(\d+\.\d+)\s+(.+)$/gm, "<h3>$1 $2</h3>")
      // Format contact sections
      .replace(/^(Contact|Contact Us):$/gm, "<h3>$1</h3>")
      // Format email and address lines
      .replace(
        /^(Email|Mailing Address):\s+(.+)$/gm,
        "<p><strong>$1:</strong> $2</p>"
      )
      // Format lists (lines starting with - or •)
      .replace(/^[-•]\s+(.+)$/gm, "<li>$1</li>")
      // Wrap consecutive list items in ul tags
      .replace(/(<li>.*<\/li>)/g, "<ul>$1</ul>")
      // Format paragraphs (non-empty lines that aren't already formatted)
      .replace(/^([^<].+)$/gm, (match) => {
        if (match.trim() && !match.startsWith("<")) {
          return `<p>${match}</p>`;
        }
        return match;
      })
      // Clean up empty paragraphs
      .replace(/<p><\/p>/g, "")
      // Remove extra spacing between sections
      .replace(/<\/h2>/g, "</h2>")
      .replace(/<\/h3>/g, "</h3>")
  );
};

export default function LegalWidgets() {
  const [expanded, setExpanded] = useState(false);
  const [selectedDocument, setSelectedDocument] =
    useState<LegalDocument | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));

  const handleDocumentClick = (document: LegalDocument) => {
    setSelectedDocument(document);
    setModalOpen(true);
  };

  const handleCloseModal = () => {
    setModalOpen(false);
    setSelectedDocument(null);
  };

  if (isMobile) {
    // On mobile, show as a simple FAB with modal
    return (
      <>
        <Fab
          color="primary"
          size="small"
          onClick={() => setModalOpen(true)}
          sx={{
            position: "fixed",
            bottom: 16,
            left: 16,
            zIndex: 1000,
            backgroundColor: theme.palette.primary.main,
            "&:hover": {
              backgroundColor: theme.palette.primary.dark,
            },
          }}
        >
          <DocumentIcon />
        </Fab>

        <Dialog
          open={modalOpen}
          onClose={handleCloseModal}
          maxWidth="md"
          fullWidth
          fullScreen={isMobile}
        >
          <DialogTitle>
            Legal Documents
            <IconButton
              aria-label="close"
              onClick={handleCloseModal}
              sx={{
                position: "absolute",
                right: 8,
                top: 8,
                color: theme.palette.grey[500],
              }}
            >
              <CloseIcon />
            </IconButton>
          </DialogTitle>
          <DialogContent>
            <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
              {documents.map((doc, index) => (
                <Paper
                  key={index}
                  sx={{
                    p: 2,
                    cursor: "pointer",
                    "&:hover": {
                      backgroundColor: theme.palette.action.hover,
                    },
                  }}
                  onClick={() => handleDocumentClick(doc)}
                >
                  <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                    {doc.icon}
                    <Typography variant="h6">{doc.title}</Typography>
                  </Box>
                </Paper>
              ))}
            </Box>
          </DialogContent>
        </Dialog>

        {/* Document Modal */}
        <Dialog
          open={selectedDocument !== null}
          onClose={handleCloseModal}
          maxWidth="md"
          fullWidth
          fullScreen={isMobile}
        >
          {selectedDocument && (
            <>
              <DialogTitle>
                {selectedDocument.title}
                <IconButton
                  aria-label="close"
                  onClick={handleCloseModal}
                  sx={{
                    position: "absolute",
                    right: 8,
                    top: 8,
                    color: theme.palette.grey[500],
                  }}
                >
                  <CloseIcon />
                </IconButton>
              </DialogTitle>
              <DialogContent>
                <Box
                  sx={{
                    maxHeight: "70vh",
                    overflowY: "auto",
                    "&::-webkit-scrollbar": {
                      width: "8px",
                    },
                    "&::-webkit-scrollbar-track": {
                      background: "#f1f1f1",
                      borderRadius: "4px",
                    },
                    "&::-webkit-scrollbar-thumb": {
                      background: "#c1c1c1",
                      borderRadius: "4px",
                      "&:hover": {
                        background: "#a8a8a8",
                      },
                    },
                  }}
                >
                  <Typography
                    variant="body1"
                    sx={{
                      whiteSpace: "pre-line",
                      fontFamily: "Inter, sans-serif",
                      fontSize: "0.9rem",
                      lineHeight: 1.2,
                      color: theme.palette.text.primary,
                      "& h1, & h2, & h3": {
                        fontWeight: 600,
                        marginTop: 0,
                        marginBottom: 0,
                        color: theme.palette.primary.main,
                      },
                      "& h1": {
                        fontSize: "1.5rem",
                        borderBottom: `2px solid ${theme.palette.primary.light}`,
                        paddingBottom: 0.5,
                        marginBottom: 0.5,
                        marginTop: 0,
                      },
                      "& h2": {
                        fontSize: "1.25rem",
                        marginTop: 0,
                      },
                      "& h3": {
                        fontSize: "1.1rem",
                        marginTop: 0,
                      },
                      "& p": {
                        marginBottom: 0,
                        textAlign: "justify",
                      },
                      "& ul, & ol": {
                        marginLeft: 2,
                        marginBottom: 0,
                        "& li": {
                          marginBottom: 0,
                          textAlign: "justify",
                        },
                      },
                      "& strong, & b": {
                        fontWeight: 600,
                        color: theme.palette.text.primary,
                      },
                      "& em, & i": {
                        fontStyle: "italic",
                        color: theme.palette.text.secondary,
                      },
                      "& blockquote": {
                        borderLeft: `4px solid ${theme.palette.primary.light}`,
                        paddingLeft: 2,
                        marginLeft: 0,
                        marginRight: 0,
                        backgroundColor: theme.palette.action.hover,
                        padding: 1.5,
                        borderRadius: "4px",
                        fontStyle: "italic",
                      },
                      "& code": {
                        backgroundColor: theme.palette.grey[100],
                        padding: "2px 4px",
                        borderRadius: "3px",
                        fontFamily: "monospace",
                        fontSize: "0.85rem",
                      },
                      "& pre": {
                        backgroundColor: theme.palette.grey[50],
                        padding: 1.5,
                        borderRadius: "4px",
                        overflowX: "auto",
                        border: `1px solid ${theme.palette.grey[200]}`,
                        fontFamily: "monospace",
                        fontSize: "0.85rem",
                      },
                    }}
                    dangerouslySetInnerHTML={{
                      __html: formatDocumentContent(selectedDocument.content),
                    }}
                  />
                </Box>
              </DialogContent>
              <DialogActions>
                <Button onClick={handleCloseModal} variant="contained">
                  Close
                </Button>
              </DialogActions>
            </>
          )}
        </Dialog>
      </>
    );
  }

  // Desktop version with expandable widgets
  return (
    <>
      <Box
        sx={{
          position: "fixed",
          bottom: 16,
          left: 16,
          zIndex: 1000,
          display: "flex",
          flexDirection: "column",
          gap: 1,
        }}
      >
        {expanded && (
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              gap: 1,
              mb: 1,
            }}
          >
            {documents.map((doc, index) => (
              <Tooltip key={index} title={`View ${doc.title}`} placement="right">
                <Paper
                  sx={{
                    p: 1.5,
                    cursor: "pointer",
                    minWidth: 200,
                    backgroundColor: theme.palette.background.paper,
                    boxShadow: theme.shadows[4],
                    "&:hover": {
                      backgroundColor: theme.palette.action.hover,
                      transform: "translateY(-1px)",
                      boxShadow: theme.shadows[8],
                    },
                    transition: "all 0.2s ease-in-out",
                  }}
                  onClick={() => handleDocumentClick(doc)}
                >
                  <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                    {doc.icon}
                    <Typography variant="body2" fontWeight={500}>
                      {doc.title}
                    </Typography>
                  </Box>
                </Paper>
              </Tooltip>
            ))}
          </Box>
        )}

        <Tooltip
          title={expanded ? "Collapse" : "Legal Documents"}
          placement="right"
        >
          <Fab
            color="primary"
            size="small"
            onClick={() => setExpanded(!expanded)}
            sx={{
              backgroundColor: theme.palette.primary.main,
              "&:hover": {
                backgroundColor: theme.palette.primary.dark,
              },
            }}
          >
            {expanded ? <CollapseIcon /> : <DocumentIcon />}
          </Fab>
        </Tooltip>
      </Box>

      {/* Document Modal */}
      <Dialog
        open={selectedDocument !== null}
        onClose={handleCloseModal}
        maxWidth="md"
        fullWidth
      >
        {selectedDocument && (
          <>
            <DialogTitle>
              {selectedDocument.title}
              <IconButton
                aria-label="close"
                onClick={handleCloseModal}
                sx={{
                  position: "absolute",
                  right: 8,
                  top: 8,
                  color: theme.palette.grey[500],
                }}
              >
                <CloseIcon />
              </IconButton>
            </DialogTitle>
            <DialogContent>
              <Box
                sx={{
                  maxHeight: "70vh",
                  overflowY: "auto",
                  "&::-webkit-scrollbar": {
                    width: "8px",
                  },
                  "&::-webkit-scrollbar-track": {
                    background: "#f1f1f1",
                    borderRadius: "4px",
                  },
                  "&::-webkit-scrollbar-thumb": {
                    background: "#c1c1c1",
                    borderRadius: "4px",
                    "&:hover": {
                      background: "#a8a8a8",
                    },
                  },
                }}
              >
                <Typography
                  variant="body1"
                  sx={{
                    whiteSpace: "pre-line",
                    fontFamily: "Inter, sans-serif",
                    fontSize: "0.9rem",
                    lineHeight: 1.2,
                    color: theme.palette.text.primary,
                    "& h1, & h2, & h3": {
                      fontWeight: 600,
                      marginTop: 0,
                      marginBottom: 0,
                      color: theme.palette.primary.main,
                    },
                    "& h1": {
                      fontSize: "1.5rem",
                      borderBottom: `2px solid ${theme.palette.primary.light}`,
                      paddingBottom: 0.5,
                      marginBottom: 0.5,
                      marginTop: 0,
                    },
                    "& h2": {
                      fontSize: "1.25rem",
                      marginTop: 0,
                    },
                    "& h3": {
                      fontSize: "1.1rem",
                      marginTop: 0,
                    },
                    "& p": {
                      marginBottom: 0,
                      textAlign: "justify",
                    },
                    "& ul, & ol": {
                      marginLeft: 2,
                      marginBottom: 0,
                      "& li": {
                        marginBottom: 0,
                        textAlign: "justify",
                      },
                    },
                    "& strong, & b": {
                      fontWeight: 600,
                      color: theme.palette.text.primary,
                    },
                    "& em, & i": {
                      fontStyle: "italic",
                      color: theme.palette.text.secondary,
                    },
                    "& blockquote": {
                      borderLeft: `4px solid ${theme.palette.primary.light}`,
                      paddingLeft: 2,
                      marginLeft: 0,
                      marginRight: 0,
                      backgroundColor: theme.palette.action.hover,
                      padding: 1.5,
                      borderRadius: "4px",
                      fontStyle: "italic",
                    },
                    "& code": {
                      backgroundColor: theme.palette.grey[100],
                      padding: "2px 4px",
                      borderRadius: "3px",
                      fontFamily: "monospace",
                      fontSize: "0.85rem",
                    },
                    "& pre": {
                      backgroundColor: theme.palette.grey[50],
                      padding: 1.5,
                      borderRadius: "4px",
                      overflowX: "auto",
                      border: `1px solid ${theme.palette.grey[200]}`,
                      fontFamily: "monospace",
                      fontSize: "0.85rem",
                    },
                  }}
                  dangerouslySetInnerHTML={{
                    __html: formatDocumentContent(selectedDocument.content),
                  }}
                />
              </Box>
            </DialogContent>
            <DialogActions>
              <Button onClick={handleCloseModal} variant="contained">
                Close
              </Button>
            </DialogActions>
          </>
        )}
      </Dialog>
    </>
  );
}
