export const exampleQuestions = [
  "Astrocyte calcium signaling in synaptic modulation",
  "Mechanisms of glial-neuronal metabolic coupling",
  "Neural oscillations in executive control networks",
  "Role of microglia in synaptic pruning dynamics",
  "NMDA receptor gating in long-term potentiation",
  "Perineuronal nets in critical period plasticity",
  "Mitochondrial calcium regulation in neuronal survival",
  "Dendritic spike generation in cortical computation",
  "Astrocyte-neuron lactate shuttle in memory consolidation",
  "MicroRNA regulation of synaptic homeostasis",
  "Dopaminergic prediction error in reinforcement learning",
  "Role of thalamocortical oscillations in consciousness",
  "Mechanisms of phase-amplitude coupling in cognition",
  "Oligodendrocyte plasticity in learning enhancement",
  "Tau protein spread via extracellular vesicles",
  "CRISPR-based modulation of neural circuit function",
  "Neuroinflammatory pathways in Parkinson's progression",
  "Astrocytic modulation of inhibitory interneurons",
  "Spike timing-dependent plasticity in decision-making",
  "Sleep spindle coordination in hippocampal replay",
  "CA1 vs CA3 encoding mechanisms in episodic memory",
  "Excitatory-inhibitory balance in cortical computation",
  "GABAergic plasticity in critical learning phases",
  "Role of the claustrum in unified conscious perception",
  "Default mode network dynamics in self-referential thought",
  "Astrocytic endfeet in blood–brain barrier regulation",
  "Cholinergic modulation of cortical oscillatory states",
  "Optogenetic dissection of fear memory engrams",
  "Role of glial cytokine signaling in depression",
  "Neuronal avalanches in large-scale brain computation",
  "Epigenetic reprogramming in neural differentiation",
  "Synaptic vesicle heterogeneity in neurotransmission fidelity",
  "Role of gamma oscillations in working memory binding",
  "Microglial surveillance in neural circuit stability",
  "Hippocampal-cortical dialogue in systems consolidation",
  "Cerebellar contributions to cognitive prediction models",
  "Astrocytic potassium buffering in network excitability",
  "Role of gap junctions in neural synchrony",
  "Neuropeptide modulation of social behavior circuits",
  "Cortical thickness variability in neurodevelopmental disorders",
  "Mechanisms of axonal transport disruption in ALS",
  "Neural coding strategies in sparse representations",
  "Glutamate transporter dysfunction in excitotoxicity",
  "Sleep-dependent synaptic renormalization mechanisms",
  "Role of astrocytic glycogen in neuronal resilience",
  "Functional significance of hippocampal sharp-wave ripples",
  "Inhibitory interneuron diversity in cortical computation",
  "Neurovascular coupling disruptions in cognitive decline",
  "Mechanisms of synaptic tagging and capture",
  "Role of glial scar formation in CNS regeneration",
  "How do astrocytes regulate extracellular glutamate clearance in synaptic microdomains?",
  "What mechanisms drive phase-locked gamma oscillations during working memory encoding?",
  "How does microglial complement signaling influence synapse elimination in development?",
  "What role does dopamine play in modulating corticostriatal synaptic plasticity?",
  "How do oligodendrocytes influence conduction velocity in adaptive learning circuits?",
  "What neural code underlies hippocampal place field remapping?",
  "How does calcium-induced calcium release contribute to dendritic excitability?",
  "What is the role of alpha oscillations in sensory gating?",
  "How do astrocytic networks influence global brain states?",
  "What mechanisms drive neuronal hyperexcitability in early Alzheimer’s disease?",
  "How does spike-frequency adaptation enable sensory prediction?",
  "What role do gap junctions play in interneuron synchrony?",
  "How does endocannabinoid signaling regulate inhibitory plasticity?",
  "What mechanisms underlie thalamocortical resonance in sleep spindles?",
  "How do neural populations encode uncertainty in Bayesian inference?",
  "What is the role of astrocytic ATP signaling in neuromodulation?",
  "How do synaptic nanocolumns organize trans-synaptic signaling fidelity?",
  "What drives glutamatergic hyperactivity in schizophrenia models?",
  "How does the subiculum mediate hippocampal output diversification?",
  "What is the role of mitochondrial fission in neurodegeneration?",
  "How do cortical columns integrate multisensory predictive signals?",
  "What mechanisms enable rapid homeostatic synaptic scaling?",
  "How does glymphatic clearance contribute to protein aggregation prevention?",
  "What is the computational role of dendritic plateau potentials?",
  "How do BDNF-TrkB pathways drive synaptic consolidation?",
  "What role does acetylcholine play in cortical plasticity gating?",
  "How do astrocytes decode neuronal firing frequency into metabolic responses?",
  "What mechanisms enable grid cell stability across environments?",
  "How does chronic neuroinflammation alter synaptic vesicle docking?",
  "What neural dynamics underlie spontaneous thought generation?",
  "How do inhibitory engrams contribute to memory suppression?",
  "What is the role of cortical oscillatory multiplexing in information routing?",
  "How do astrocytic lipid metabolism pathways influence neuronal survival?",
  "What mechanisms underlie remyelination failure in multiple sclerosis?",
  "How do ketone bodies alter neuronal firing energetics?",
  "What neural substrates enable time perception in the brain?",
  "How do CRISPR base editors impact neuronal gene expression variability?",
  "What drives synaptic clustering on dendritic branches?",
  "How does glial cytokine signaling contribute to depressive phenotypes?",
  "What is the computational function of hippocampal replay sequences?",
  "How do interneuron subclasses regulate oscillatory phase alignment?",
  "What mechanisms govern calcium wave propagation in glial syncytia?",
  "How does GABAergic tonic inhibition shape sensory discrimination?",
  "What is the role of astrocytes in regulating neurovascular coupling under hypoxia?",
  "How do cortico-striatal loops implement action selection policies?",
  "What cellular processes mediate tau uptake and propagation?",
  "How does NMDA receptor subunit composition influence synaptic fidelity?",
  "What is the mechanism of synaptogenesis in adult-born neurons?",
  "How do oscillatory bursts contribute to conscious access?",
  "What drives large-scale cortical state transitions during anesthesia?"
];

// Function to get a random subset of questions
export const getRandomQuestions = (count: number = 3): string[] => {
  const shuffled = [...exampleQuestions].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};
